name: Pipeline Scan with Verademo Maven Build

on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    #Check out report under $GITHUB_WORKSPACE - job can access and clone
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file app/pom.xml
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
      # Artifact name
        name: verademo
        # A file, directory, or wildcard pattern that describes what to upload
        path: /home/runner/work/verademo/verademo/app/target/verademo.war
        retention-days: 5

    - name: Veracode Pipeline-Scan
      # You may pin to the exact commit or the version.
      # uses: veracode/Veracode-pipeline-scan-action@c94abab5dc83cccc825c05120b746835fc6f673a
      uses: veracode/Veracode-pipeline-scan-action@v1.0.16
      with:
        # vid
        vid: ${{ secrets.VERACODE_API_ID }}
        # vkey
        vkey: ${{ secrets.VERACODE_API_KEY }}
        # Filename of the packaged application to upload and scan.
        file: app/target/verademo.war
        # GITHUB_TOKEN or a repo scoped PAT.
        token: ${{ secrets.GH_TOKEN }} # default is ${{ github.token }}
        # Name of the security policy to download as a file. Required only if you want to download the configuration for a custom policy defined by your organization. After downloading the policy, you can provide this file in a subsequent command using the policy_file parameter.
        #request_policy: # optional
        # Fail the pipeline job if the scan finds flaws of the specified severities. Enter a comma-separated list of severities in quotation marks.
        #fail_on_severity: # optional
        # Fail the pipeline job if the scan finds flaws of the specified CWEs. Enter a comma-separated list of CWE IDs.
        #fail_on_cwe: # optional
        # Filter the flaws that exist in the specified baseline file and show only the additional flaws in the current scan.
        #baseline_file: # optional
        # Name of the Veracode default policy rule to apply to the scan results. You can only use this parameter with a Veracode default policy.
        #policy_name: # optional
        # Name of the local policy file you want to apply to the scan results. To download this file, use the --request_policy parameter.
        #policy_file: # optional
        # Amount of time, in minutes, for the Pipeline Scan to wait before reporting an unsuccessful scan if the scan does not complete. Default is 60 minutes, which is also the maximum value.
        #timeout: # optional
        # Enter true to show detailed messages for each issue in the results summary.
        #issue_details: # optional
        # Enter true to show a human-readable results summary on the console. Default is true.
        #summary_display: # optional
        # Enter true to show the JSON containing the scan results on the console. Default is false.
        #json_display: # optional
        # Enter true to display detailed messages in the scan results. Default is false.
        #verbose: # optional
        # Enter true to save the scan results as a human-readable file. Default is false.
        summary_output: true # optional
        # Enter the filename of the scan results summary file. The file is stored in the current directory. Default is results.txt.
        summary_output_file: results.txt # optional
        # Enter true to save the scan results in JSON format. Default is true.
        #json_output: # optional
        # Rename the JSON file that contains the scan results. The file is stored in the current directory. Default filename is results.json.
        #json_output_file: # optional
        # Enter the filename in the current directory to save results that violate pass-fail criteria. Default is filtered_results.json.
        #filtered_json_output_file: # optional
        # Enter the name of the CI/CD code repository that runs a Pipeline Scan. This parameter adds the repository name to the scan results, which can help you track scans across repositories.
        project_name: Verademo # optional
        # Enter the source control URL for the CI/CD code repository that runs a Pipeline Scan.
        project_url: https://github.com/JPBryant001/verademo # optional
        # Enter the source control reference, revision, or branch for the CI/CD code repository that runs a Pipeline Scan.
        project_ref: main # optional
        # Enter the [application profile](https://docs.veracode.com/r/request_profile) ID for the application you want to upload and scan.
        #app_id: # optional
        # Enter one these values, which are case-sensitive, for the type of development stage: Development, Testing, Release.
        #development_stage: # optional
        # Enable debug mode. 1 for on
        debug: 1 # optional
        # Enable the storage of a baseline file. Takes true or fales
        store_baseline_file: true # optional
        # Enter the branch name where the baseline file should be stored
        store_baseline_file_branch: baseline # optional
        # From which results should the baseline file be created. standard = full results || filtered = filtered results
        create_baseline_from: standard # optional
        # Fail the build upon findings. Takes true or false
        fail_build: false # optional
